### ISSUE TITLE
source code license for shape file reader

### ISSUE THREAD

**Issue by NRCMERO** [NRCMERO/MDC_LocLookup#11]
The shapefile reader code
https://github.com/NRCMERO/MDC_LocLookup/tree/master/LocLookup/app/src/main/java/com/openDC/loclookup/model/shape_files
is practically the same as this library's
https://github.com/diwi/diewald_shapeFileReader/tree/master/diewald_shapeFileReader/src/diewald_shapeFile,
which, is perfectly fine.

The issue here is that the source itself isn't being used but a decompiled version of the JAR library
https://github.com/diwi/diewald_shapeFileReader/tree/master/diewald_shapeFileReader/library,
using the CFR decompiler http://www.benf.org/other/cfr/.
This makes it unobvious that we're using someone else's code.
The better approach is to use the source of the library or at least to explain the situation in the docs.

**Comment by HamzehSoboh** [comment]
Rolled back to the .jar lib
I've reversed it just to be able to debug encoding until it's resolved.

**Comment by NRCMERO** [comment]
@devnrc please confirm

**Comment by devnrc** [comment]
@NRCMERO, confirmed. Thanks, @HamzehSoboh.
