### ISSUE TITLE
code organization

### ISSUE THREAD

**Issue by NRCMERO** [NRCMERO/MDC_LocLookup#12]
Move all dependencies (listable, maputils, popup, ripple, and now diewald_shapeFile) to a dedicated directory.

**Comment by HamzehSoboh** [comment]
Please clarify why to add to a dedicated directory

**Comment by HamzehSoboh** [comment]
I've removed 'ripple' library since it is not necessary. And 'listable is my own, I've implemented it from scratch to help making lists implementation much easier and faster.

Remains 'maputils' and 'popup' which is OK to be there since we're publishing a sample, not a library.

**Comment by devnrc** [comment]
It's an optional step to make things a bit more organized. Feel free to skip it.

Regarding 'listable', nice work!
Although as it it now it's hard to tell that it was yours given that your files are mingled with the [StickyHeaders](https://github.com/ShamylZakariya/StickyHeaders/tree/master/stickyheaders/src/main/java/org/zakariya/stickyheaders) library and under its directories. It's highly recommended to separate the two so we can all know that awesome code is yours! Thanks.

**Comment by HamzehSoboh** [comment]
Yes I know, done this morning with the new push.
Since all lists are simple, no sticky headers.

**Comment by NRCMERO** [comment]
@devnrc great if you could have a look at the latest commit and close this if addressed

**Comment by devnrc** [comment]
Done.
