### ISSUE TITLE
license issue

### ISSUE THREAD

**Issue by NRCMERO** [NRCMERO/MDC_LocLookup#13]
double-check and document the font license (Arabia Weather Regular.ttf) and the logo license

**Comment by HamzehSoboh** [comment]
For the logo, I've selected this one
https://www.iconfinder.com/icons/299035/marker_icon#size=128
Which is totally free.

But for the font, I think we have to contact arabia-whether
http://jo.arabiaweather.com/
And take their permission to use the font,
Or search for a new good free one that works for Arabic and English.

**Comment by NRCMERO** [comment]
logo looks good.  please address the font license issue.

**Comment by devnrc** [comment]
Cool. All we need to do now is simply add links to the [logo](https://www.iconfinder.com/icons/299035/marker_icon#size=128) and the [new font just picked](https://github.com/Gue3bara/Cairo) in the [readme file](https://github.com/NRCMERO/MDC_LocLookup/issues/6).

**Comment by NRCMERO** [comment]
@HamzehSoboh looks like the last comment from @devnrc is outstanding?

**Comment by HamzehSoboh** [comment]
OK, then I'll add those links at the end of the file, right?

**Comment by HamzehSoboh** [comment]
And I've written the documentation first in wiki part, I think I should keep only readme and clear the wiki.

**Comment by NRCMERO** [comment]
ok

**Comment by NRCMERO** [comment]
@devnrc can you close this if we're sorted?

**Comment by HamzehSoboh** [comment]
Done from my side.
