### ISSUE TITLE
Outside assigned area should be returned as value

### ISSUE THREAD

**Issue by NRCMERO** [NRCMERO/MDC_LocLookup#14]
When the device is in a location outside the scope of loaded maps, it should return the value "Location Outside Mapped Area" to the kobo/mobenzi.  This will allow supervisors to see what the issue is when they see the data.  it will also allow the survey to continue if the field is required.

**Comment by HamzehSoboh** [comment]
Will this message be the same in Arabic mode?

**Comment by NRCMERO** [comment]
no.  always english

**Comment by NRCMERO** [comment]
sorted
