### ISSUE TITLE
welcome message change

### ISSUE THREAD

**Issue by NRCMERO** [NRCMERO/MDC_LocLookup#4]
Changes to welcome screen: Change "Welcome to LocLookup" to "Welcome to MDC Location Look Up.  This application works with your mobile data capture application.  It will look up the name of the area where you are and return the name of that location to the mobile data capture application."

**Comment by HamzehSoboh** [comment]
I suggest to add this to the middle of the screen, as long as no maps have been added.
When there's at least one item, then the message will disappear.
What do you see?

**Comment by NRCMERO** [comment]
sounds good
