### ISSUE TITLE
APP should work with these sample shapefiles

### ISSUE THREAD

**Issue by NRCMERO** [NRCMERO/MDC_LocLookup#5]
https://data.humdata.org/dataset/syrian-arab-republic-administrative-boundaries-populated-places
 
https://data.humdata.org/dataset/kenya-elections
 
https://data.humdata.org/dataset/lebanon-admin-level-3-boundaries
 
https://data.humdata.org/dataset/djibouti-admin-level-3-boundaries
 
https://data.humdata.org/dataset/pakistan-admin-level-3-boundaries
 
https://data.humdata.org/dataset/uganda-admin-level-3-boundaries

**Comment by HamzehSoboh** [comment]
For me, it worked with all samples except Uganda.
After debugging, it was because the shape files couldn't be parsed by shape file reader.
Attached the error.

![screen shot 2017-01-03 at 10 32 51 am](https://cloud.githubusercontent.com/assets/8372679/21603315/efbfc888-d1a4-11e6-90b9-802268d37650.png)

**Comment by HamzehSoboh** [comment]
However, I tried Uganda shape files from [another source](http://mapeastafrica.com/countries/east-africa-shapefiles/uganda-shapefiles/)
And worked perfectly.

Also, now I'm showing a message to the user telling him when the shape files couldn't be read, to go and fetch them from another source. And the map will not be added to the list.

**Comment by NRCMERO** [comment]
https://data.humdata.org/dataset/syrian-arab-republic-administrative-boundaries-populated-places
works
https://data.humdata.org/dataset/kenya-elections
Needs further testing, but may be an issue with the shape file format

https://data.humdata.org/dataset/lebanon-admin-level-3-boundaries
works

https://data.humdata.org/dataset/djibouti-admin-level-3-boundaries
returns only admn 3 because of shape file

https://data.humdata.org/dataset/pakistan-admin-level-3-boundaries
works

https://data.humdata.org/dataset/uganda-admin-level-3-boundaries
doesn't work because of shape file format
