### ISSUE TITLE
Display the sys messages (GPS not on, access storage, etc) in arabic and english depending on device lang settings

### ISSUE THREAD

**Issue by NRCMERO** [NRCMERO/MDC_LocLookup#7]
Arabic = Arabic
all other lang = english

**Comment by HamzehSoboh** [comment]
I suggest making it independent from device language.
I'll add a the language (Ar, En) to the header, and the user can swap between the languages from there. 

Since having a system with English language doesn't mean a user with advanced English skills.
What do you see?

**Comment by NRCMERO** [comment]
change back to original.  please use the device lang.  because this may change from end user to end user and we don't want the end user into the loclookup application, better the lang setting is automatic
