### ISSUE TITLE
git wiki on this repo for building a compatible ODK form

### ISSUE THREAD

**Issue by NRCMERO** [NRCMERO/MDC_LocLookup#8]

**Comment by HamzehSoboh** [comment]
I think it's done (see wiki),
Please check and advice.

**Comment by HibaYaghmour** [comment]
Hi Hamzeh,
I tried to follow the wiki on how to build a form in kobo but there isn't a step on how to add the button which will launch the app. Please advice..

**Comment by HamzehSoboh** [comment]
It automatically appears once you fill the appearance field from question settings.

Sent from Yahoo Mail on Android 
 
  On Wed, Jan 4, 2017 at 3:22 PM, HibaYaghmour<notifications@github.com> wrote:   
Hi Hamzeh,
I tried to follow the wiki on how to build a form in kobo but there isn't a step on how to add the button which will launch the app. Please advice..

**Comment by HamzehSoboh** [comment]
BTW, if you're editing an already opened form, then it may not take the effect directly. You have to go Get Blank Form again for caching issues in KoBo


Sent from Yahoo Mail on Android 
 
  On Wed, Jan 4, 2017 at 3:24 PM, Hamzeh Soboh<hamztaxerror@yahoo.com> wrote:   It automatically appears once you fill the appearance field from question settings.

Sent from Yahoo Mail on Android 
 
  On Wed, Jan 4, 2017 at 3:22 PM, HibaYaghmour<notifications@github.com> wrote:   
Hi Hamzeh,
I tried to follow the wiki on how to build a form in kobo but there isn't a step on how to add the button which will launch the app. Please advice..

**Comment by HibaYaghmour** [comment]
I'm using a new form but the button didn't appear

Kindly check the screen shots for my application and console versions of the form

![image](https://cloud.githubusercontent.com/assets/24788642/21643867/5b4f067e-d293-11e6-9fcf-10a288b141bd.png)

![image](https://cloud.githubusercontent.com/assets/24788642/21643887/744f4cf6-d293-11e6-8afa-0a8d618fe3f1.png)

Sorry for the huge images !

**Comment by HamzehSoboh** [comment]
add ex: at the beginning of the input field before 'com'
it's a part of the value

**Comment by HamzehSoboh** [comment]
Add ex: at the beginningIt's a part of the input dataNot (exampleHope it helps

Sent from Yahoo Mail on Android 
 
  On Wed, Jan 4, 2017 at 3:36 PM, HibaYaghmour<notifications@github.com> wrote:   
I'm using a new form but the button didn't appear

Kindly check the screen shots for my application and console versions of the form

**Comment by HibaYaghmour** [comment]
Oh sorry it's my bad. It's working fine now !

I think the wiki is clear. Thank you !

**Comment by HamzehSoboh** [comment]
Welcome!
